package com.example.brain

import android.util.Log
import com.example.ai.AiEngine
import java.util.Locale
import kotlinx.coroutines.TimeoutCancellationException
import kotlinx.coroutines.withTimeout

/**
 * Natural conversational response layer for D-VEX Smart Brain.
 *
 * V3 — LLM IS THE LANGUAGE AUTHORITY:
 * Hardcoded control lives in the intent/tool/verification layers only. Every
 * user-facing SENTENCE is generated by the LLM:
 * - ACTION REQUEST: verified tool result + user language + context -> LLM phrasing.
 * - NORMAL CONVERSATION: user input + history + memory -> LLM directly.
 * The generator owns NO conversational templates. The only hardcoded strings are
 * the emergency fallback (used exclusively when the LLM engine is missing or the
 * call failed) and deterministic confirmation prompts (control logic).
 *
 * Hard guarantees preserved:
 * 1. NEVER FABRICATES DATA: action prompts pass only real tool numbers and
 *    forbid the model from inventing facts. The model phrases; it does not compute.
 * 2. NEVER GOES SILENT: LLM failure (timeout, blank, missing key, error) falls
 *    back to one minimal honest line — clearly flagged in logs as not-AI.
 * 3. NEVER HANGS: a hard 8s timeout bounds the LLM call.
 * 4. NON-BLOCKING: generateResponse is suspend; callers already run in coroutines.
 * 5. NO TOOL-LOGIC CHANGES: intent decides WHAT happens; the LLM decides HOW it's said.
 */
class DvexResponseGenerator(
  private val aiEngine: AiEngine? = null
) {

  /**
   * Estimates conversational tone from the user's words and conversational cues.
   * Passed to the LLM as warmth/styling signal — no longer a branch selector for
   * pre-written lines.
   */
  fun estimateTone(userInput: String): EstimatedTone {
    val text = userInput.lowercase(Locale.ROOT)
    if (text.isBlank()) return EstimatedTone.NEUTRAL

    // Urgent cues
    if (text.contains("urgent") || text.contains("urgently") || text.contains("emergency") ||
        text.contains("immediately") || text.contains("right now") || text.contains("asap") ||
        text.contains("hurry") || text.contains("quick") || text.contains("quickly") ||
        text.contains("seekiram") || text.contains("seekirama") || text.contains("udane") ||
        text.contains("ippove") || text.contains("avacharam") || text.contains("vegam") ||
        text.contains("vegama") || text.contains("fast") || text.contains("speed") ||
        text.contains("உடனே") || text.contains("சீக்கிரம்") || text.contains("சீக்கிரமா") ||
        text.contains("அவசரம்")
    ) {
      return EstimatedTone.URGENT
    }

    // Frustrated cues
    if (text.contains("annoying") || text.contains("stupid") || text.contains("worst") ||
        text.contains("waste") || text.contains("hate") || text.contains("angry") ||
        text.contains("not working") || text.contains("useless") || text.contains("shut up") ||
        text.contains("kaduppa") || text.contains("kaduppu") || text.contains("kadupethatha") ||
        text.contains("erichal") || text.contains("erichala") || text.contains("worstu") ||
        text.contains("wasteu") || text.contains("vela seiyala") || text.contains("vela pakkala") ||
        text.contains("ennada idhu") || text.contains("thirumba thirumba") || text.contains("frustrated") ||
        text.contains("frustrating") || text.contains("irritat") || text.contains("tension") ||
        text.contains("கடுப்பு") || text.contains("எரிச்சல்") || text.contains("வேலை செய்யவில்லை") ||
        text.contains("வெறுப்பு") ||
        text.contains("மாட்டேங்குது") || text.contains("சரியா போகவே") || text.contains("சரியா போகல") ||
        text.contains("sariya pogala") || text.contains("sariya poagala") ||
        text.contains("pogave mattenguthu") || text.contains("pogave mattenkuthu") ||
        text.contains("ellame sariya") || text.contains("ellam sariya")
    ) {
      return EstimatedTone.FRUSTRATED
    }

    // Confused cues
    if (text.contains("what do you mean") || text.contains("confused") || text.contains("confusing") ||
        text.contains("don't understand") || text.contains("dont understand") || text.contains("how come") ||
        text.contains("puriyala") || text.contains("purila") || text.contains("puriyave illa") ||
        text.contains("enna solra") || text.contains("enna soldra") || text.contains("enna aachu") ||
        text.contains("theriyala") || text.contains("not clear") || text.contains("புரியவில்லை") ||
        text.contains("என்ன சொல்றீங்க") || text.contains("என்ன சொல்ற") || text.contains("விளங்கவில்லை")
    ) {
      return EstimatedTone.CONFUSED
    }

    // Excited cues
    if (text.contains("wow") || text.contains("amazing") || text.contains("let's go") ||
        text.contains("unbelievable") || text.contains("vera level") || text.contains("mass kaatita") ||
        text.contains("massu") || text.contains("mass") || text.contains("excited") ||
        text.contains("awesome") || text.contains("fire") || text.contains("superb") ||
        text.contains("brilliant") || text.contains("marana mass") || text.contains("sema mass") ||
        text.contains("வேற லெவல்") || text.contains("வேற மாறி")
    ) {
      return EstimatedTone.EXCITED
    }

    // Happy / Grateful cues
    if (text.contains("super") || text.contains("great") || text.contains("wonderful") ||
        text.contains("happy") || text.contains("glad") || text.contains("thank you so much") ||
        text.contains("love it") || text.contains("semma") || text.contains("kalakkita") ||
        text.contains("arputham") || text.contains("good job") || text.contains("well done") ||
        text.contains("romba nandri") || text.contains("மகிழ்ச்சி") || text.contains("சூப்பர்") ||
        text.contains("அற்புதம்") || text.contains("நன்றி")
    ) {
      return EstimatedTone.HAPPY
    }

    // Sad / Low cues
    if (text.contains("sad") || text.contains("depressed") || text.contains("feeling down") ||
        text.contains("feeling low") || text.contains("bad day") || text.contains("unhappy") ||
        text.contains("upset") || text.contains("heartbroken") || text.contains("crying") ||
        text.contains("sogam") || text.contains("sogama") || text.contains("kashtama") ||
        text.contains("vali") || text.contains("vali thaangala") || text.contains("kavalaya") ||
        text.contains("சோகம்") || text.contains("கஷ்டமா இருக்கு") || text.contains("மனசு சரியில்லை") ||
        text.contains("வருத்தம்") || text.contains("கவலை")
    ) {
      return EstimatedTone.SAD
    }

    return EstimatedTone.NEUTRAL
  }

  /**
   * Generates the final spoken/displayed reply.
   *
   * Flow:
   * 1. Repeat requests replay the last spoken response directly (no LLM).
   * 2. Low-confidence speech gets a short deterministic clarification (no LLM —
   *    these must be instant and never hallucinate an action).
   * 3. Everything else is phrased by the LLM from a factual prompt; on any LLM
   *    failure the tool's own honest result or a simple fallback is returned.
   *
   * The [memoryHint] is an optional pre-rendered string of remembered user facts
   * (preferred name, likes, style) from the existing memory store — passed into
   * the prompt so the LLM can personalize naturally.
   */
  suspend fun generateResponse(
    intent: DvexIntent,
    toolResult: DvexToolResult,
    language: DetectedLanguage,
    userInput: String = "",
    context: ConversationContext? = null,
    tone: EstimatedTone = estimateTone(userInput),
    memoryHint: String? = null,
    /**
     * True when speech recognition was unsure of the words. The turn still goes to
     * the LLM (a real question must be answerable); the model is told the text may
     * be garbled and may ask for a repeat naturally, in the user's language.
     */
    unclearInput: Boolean = false
  ): String {
    val lowerInput = userInput.lowercase(Locale.ROOT).trim()
    Log.i(TAG, "[D-VEX][RESPONSE] generateResponse for input=\"$userInput\" (intent=${intent::class.simpleName}, tool=${toolResult.toolName}, lang=$language)")

    // 1. Context Continuity: Repeat requests (kept as-is; no LLM needed)
    if (context != null && (lowerInput == "repeat that" || lowerInput == "what did you say" ||
            lowerInput == "enna sonna" || lowerInput == "திரும்ப சொல்லு" || lowerInput == "repeat")
    ) {
      val lastSaid = context.lastSpokenResponse
      if (!lastSaid.isNullOrBlank()) {
        // Deterministic echo of the previous reply (playback control, not
        // conversational authoring). Language-matched, and deliberately without
        // the old honorific filler.
        return when (language) {
          DetectedLanguage.TAMIL -> "நான் சொன்னது: $lastSaid"
          DetectedLanguage.TANGLISH -> "Naan sonnathu: $lastSaid"
          DetectedLanguage.ENGLISH -> "I said: $lastSaid"
        }
      }
    }

    // 2. Uncertain speech / garbled transcription: short, instant, deterministic
    // clarification. Never invents missing words or facts, so it stays LLM-free.
    if (intent is DvexIntent.LowConfidence) {
      val response = sanitizeFinalReply(generateClarification(language, intent.candidateIntent), language)
      Log.i(TAG, "Generated clarification ($language, tone=$tone): \"$response\"")
      return response
    }

    // 3. LLM path — THE SINGLE RESPONSE AUTHORITY.
    // Normal conversation/general questions get a dedicated pure-conversation
    // prompt (no tool scaffolding); action results get the verified-result prompt.
    // The LLM owns WHAT is said and HOW: wording, length, tone, follow-ups,
    // emotional handling, and language (English/Tamil/Tanglish mirroring).
    val engine = aiEngine
    if (engine != null) {
      val isConversation = toolResult.toolName == "conversation" || toolResult.toolName == "general_qa"
      val prompt = if (isConversation) {
        buildConversationPrompt(
          language = language,
          userInput = userInput,
          context = context,
          memoryHint = memoryHint,
          tone = tone,
          unclearInput = unclearInput
        )
      } else {
        buildResponsePrompt(intent, toolResult, language, userInput, tone, context, memoryHint)
      }
      Log.i(TAG, "[D-VEX][AI] request started (${if (isConversation) "CONVERSATION" else "ACTION"} path)")
      val llmReply = try {
        withTimeout(LLM_TIMEOUT_MS) { engine.generate(prompt) }
      } catch (e: TimeoutCancellationException) {
        Log.w(TAG, "[D-VEX][AI] LLM response timed out after ${LLM_TIMEOUT_MS}ms; using emergency fallback")
        null
      } catch (e: Exception) {
        Log.w(TAG, "[D-VEX][AI] LLM engine threw ${e.javaClass.simpleName}: ${e.message}; using emergency fallback")
        null
      }
      if (!llmReply.isNullOrBlank()) {
        val sanitized = sanitizeFinalReply(llmReply, language)
        Log.i(TAG, "[D-VEX][AI] success")
        Log.i(TAG, "[D-VEX][AI] generated=\"$sanitized\"")
        return sanitized
      }
      Log.w(TAG, "[D-VEX][AI] LLM returned null/blank; using EMERGENCY fallback (not AI-generated)")
    } else {
      Log.w(TAG, "[D-VEX][AI] no LLM engine available; using EMERGENCY fallback (not AI-generated)")
    }

    // 4. EMERGENCY fallback — reached ONLY when the LLM engine is missing (no API
    // key) or the LLM call genuinely failed. Minimal and honest; it never imitates
    // AI conversation and never repeats varied canned chit-chat.
    return fallbackResponse(intent, toolResult, language).also {
      Log.w(TAG, "[D-VEX][RESPONSE] emergency fallback=\"$it\"")
    }
  }

  /**
   * Last-mile leak guard applied to EVERY reply about to be spoken/displayed.
   * Internal metadata ("Conversation: greeting", "tool_result", bracketed intent
   * tags, JSON-ish debug payloads) must never reach the user, regardless of which
   * layer produced the text. When the sanitized text would be empty, a safe
   * language-aware line is returned instead.
   *
   * Visible for testing: pins the exact sanitization contract.
   */
  fun sanitizeFinalReply(text: String, language: DetectedLanguage = DetectedLanguage.ENGLISH): String {
    var cleaned = text.trim()

    // Internal structural labels the old pipeline could emit.
    val metaLabel = Regex(
      "(?i)^\\s*(conversation(\\s*type)?|general\\s*question|tool\\s*result|intent" +
        "|spoken\\s*data|result)\\s*[:=]\\s*"
    )
    if (metaLabel.containsMatchIn(cleaned)) {
      cleaned = metaLabel.replace(cleaned, "")
    }

    // Bracketed routing tags like [greeting] / (general_qa) / <how_are_you>.
    cleaned = BRACKETED_TAG_REGEX.replace(cleaned, " ")

    // Bare internal category words that a broken layer could emit alone. The MCP
    // status names (UNVERIFIED / VERIFIED_SUCCESS) are included: they are internal
    // verification vocabulary, never something D-VEX says.
    if (cleaned.trim().lowercase(Locale.ROOT) in setOf(
        "greeting", "identity", "how_are_you", "capabilities", "thanks",
        "goodbye", "joke", "science", "space", "productivity",
        "general", "general_qa", "conversation", "tool_result", "success", "failed",
        "unverified", "verified_success"
      )
    ) {
      cleaned = ""
    }

    // Strip wrapped quotes a model sometimes adds.
    cleaned = cleaned.trim().removeSurrounding("\"").trim()

    return cleaned.ifBlank {
      when (language) {
        DetectedLanguage.TAMIL -> "மன்னிக்கவும், இப்போது பதிலளிக்க முடியவில்லை."
        DetectedLanguage.TANGLISH -> "Sorry, konjam mudiyala. Thirumba sollunga."
        DetectedLanguage.ENGLISH -> FALLBACK_TROUBLE
      }
    }
  }

  // =========================================================================
  // --- Prompt construction ---
  // =========================================================================

  /**
   * Builds the response-generation prompt. Contains ONLY facts D-VEX actually
   * established: the executed action, the real tool result, the user's verbatim
   * utterance, tone, and optional memory. The model is explicitly forbidden from
   * inventing numbers, names, or outcomes.
   */
  fun buildResponsePrompt(
    intent: DvexIntent,
    toolResult: DvexToolResult,
    language: DetectedLanguage,
    userInput: String,
    tone: EstimatedTone,
    context: ConversationContext?,
    memoryHint: String?
  ): String {
    val sb = StringBuilder()
    sb.append(
      "You are D-VEX, a personal voice assistant on the user's phone. " +
        "Write the reply the assistant should say out loud next.\n\n"
    )
    sb.append("STRICT RULES:\n")
    sb.append("- Reply in 1-2 short natural sentences. No lists, no markdown, no emojis.\n")
    sb.append(
      "- Mirror the user's own language, script, and style EXACTLY as they used it " +
        "(Tamil script, Tanglish romanized Tamil, English, or a natural mix). " +
        "Do NOT add titles or honorifics like \"Sir\" unless the user used one first.\n"
    )
    sb.append("- ").append(languageTarget(language))
    sb.append("- ").append(spokenDeliveryRule())
    sb.append("- ").append(deviceBoundaryRule())
    sb.append(
      "- Use ONLY the facts given below. NEVER invent or change numbers, times, " +
        "weather values, names, or outcomes. If the action failed or was not " +
        "found, say so plainly without sugarcoating it into a success.\n"
    )
    sb.append("- Sound like a warm, smart human assistant, not a scripted bot.\n")
    sb.append(
      "- NEVER output internal metadata, intent labels, tool names, status codes " +
        "or bracketed routing tags (for example \"Conversation: greeting\"). " +
        "Reply only with real spoken language.\n\n"
    )

    sb.append("WHAT JUST HAPPENED: ${describeAction(intent, toolResult)}\n")
    sb.append("RESULT: ${toolResult.status.name} — ${stripHonorifics(toolResult.message)}\n")
    if (toolResult.spokenText.isNotBlank() && toolResult.spokenText != toolResult.message) {
      sb.append("SPOKEN DATA: ${stripHonorifics(toolResult.spokenText)}\n")
    }
    if (userInput.isNotBlank()) {
      sb.append("USER SAID (verbatim, mirror this language and tone): \"$userInput\"\n")
    }
    val toneWord = when (tone) {
      EstimatedTone.URGENT -> "urgent — be prompt and reassuring, act like it's already being handled"
      EstimatedTone.FRUSTRATED -> "frustrated — stay calm, acknowledge it, offer to fix it step by step"
      EstimatedTone.SAD -> "low/sad — be gentle and supportive"
      EstimatedTone.CONFUSED -> "confused — be extra clear and simple"
      EstimatedTone.EXCITED -> "excited — match the energy, keep it brief"
      EstimatedTone.HAPPY -> "happy/grateful — be warm, enjoy it with them"
      EstimatedTone.NEUTRAL -> "neutral"
    }
    sb.append("USER TONE SOUNDS: $toneWord\n")
    if (!memoryHint.isNullOrBlank()) {
      sb.append("REMEMBERED ABOUT THE USER: $memoryHint\n")
    }
    context?.lastSpokenResponse?.takeIf { it.isNotBlank() }?.let {
      sb.append("YOUR PREVIOUS REPLY (for continuity, don't repeat it): \"$it\"\n")
    }

    sb.append("\nReply now with ONLY the spoken reply text.")
    return sb.toString()
  }

  /** Short factual description of the executed action for the prompt. */
  private fun describeAction(intent: DvexIntent, toolResult: DvexToolResult): String {
    return when (intent) {
      is DvexIntent.OpenApp -> "The user asked to open the app \"${intent.appName}\"."
      is DvexIntent.CallContact -> "The user asked to call \"${intent.recipient}\"."
      is DvexIntent.SendMessage ->
        if (intent.isWhatsApp) {
          "The user asked to send a WhatsApp message to \"${intent.recipient}\"" +
            (intent.messageText?.let { " saying \"$it\"" } ?: "") + "."
        } else {
          "The user asked to send a message to \"${intent.recipient}\"" +
            (intent.messageText?.let { " saying \"$it\"" } ?: "") + "."
        }
      is DvexIntent.SendEmail -> "The user asked to send an email to \"${intent.recipient}\"."
      is DvexIntent.GetWeather ->
        "The user asked for the weather" +
          (intent.location?.let { " in $it" } ?: "") + (if (intent.isTomorrow) " for tomorrow" else "") + "."
      is DvexIntent.GetTime -> "The user asked for the current time."
      is DvexIntent.Calculate -> "The user asked to calculate \"${intent.expression}\"."
      is DvexIntent.SearchWeb -> "The user asked to search the web for \"${intent.query}\"."
      is DvexIntent.PlayYoutubeVideo -> "The user asked to play \"${intent.query}\" on YouTube."
      is DvexIntent.SetAlarm -> "The user asked to set an alarm."
      is DvexIntent.SetTimer -> "The user asked to set a timer."
      is DvexIntent.RememberFact -> "The user asked D-VEX to remember: \"${intent.fact}\"."
      is DvexIntent.RecallMemory -> "The user asked what D-VEX remembers."
      is DvexIntent.GetRecentApps -> "The user asked for recently used apps."
      is DvexIntent.WakeGreeting -> "The user woke D-VEX with a greeting."
      is DvexIntent.Conversation -> "The user said: \"${intent.statement}\"."
      is DvexIntent.GeneralQuestion -> "The user asked: \"${intent.question}\"."
      is DvexIntent.MultiStep -> "The user gave a two-step command (e.g. open an app and search inside it)."
      else -> "The user made a device-control request (\"${toolResult.toolName}\")."
    }
  }

  /**
   * Deterministic honorific cleanup for text authored by the TOOL/AGENT layer.
   * Those layers historically hardcoded ", Sir" into every device result; D-VEX
   * never addresses the user that way unless the user did it first. Applied to
   * tool text BEFORE it is handed to the model (so the model cannot mirror it) and
   * to every pre-written fallback line. LLM output itself is left alone, because
   * mirroring a user's own honorific is legitimate.
   */
  fun stripHonorifics(text: String): String {
    if (text.isBlank()) return text
    return HONORIFIC_LEADING_REGEX.replace(text, "")
      .let { HONORIFIC_INLINE_REGEX.replace(it, "") }
      .replace(WHITESPACE_RUN_REGEX, " ")
      .trim()
  }

  // =========================================================================
  // --- Deterministic fallback (LLM unavailable) ---
  // =========================================================================

  /**
   * Simple honest fallback used when the LLM path is unavailable or failed.
   * Prefers the tool's own spoken text when it carries the real result (weather
   * numbers, time, confirmation prompts) so real data still reaches the user;
   * for conversation/general-question tool results, uses a lightweight structural
   * fallback mapped by language; otherwise a short static line. Never fabricates.
   */
  private fun fallbackResponse(intent: DvexIntent, toolResult: DvexToolResult, language: DetectedLanguage): String {
    // EMERGENCY-ONLY fallback: reached exclusively when the LLM engine is missing
    // (no API key) or the LLM call genuinely failed. D-VEX's language is owned by
    // the LLM; this never imitates conversation and never rotates canned variants.
    //
    // CONFIRMATION prompts are CONTROL LOGIC, not conversation: the tool layer
    // authors them deterministically ("Call Amma?" / permission notices). They pass
    // through sanitized even when the LLM is down — safety must never depend on an
    // AI call succeeding.
    if (toolResult.status == DvexToolStatus.CONFIRMATION_REQUIRED && !toolResult.confirmationPrompt.isNullOrBlank()) {
      return sanitizeFinalReply(stripHonorifics(toolResult.confirmationPrompt), language)
    }
    if (toolResult.spokenText.isNotBlank() && toolResult.spokenText != toolResult.message) {
      return sanitizeFinalReply(stripHonorifics(toolResult.spokenText), language)
    }

    // Conversation/QA results carry NO user-facing text (their spokenText is empty
    // and their message is internal routing metadata). Without the LLM there is
    // nothing to say: ONE minimal honest line, identical every time.
    if (toolResult.toolName == "conversation" || toolResult.toolName == "general_qa") {
      return when (language) {
        DetectedLanguage.TAMIL -> "இணைப்பு இல்லை — அதனால் இப்போது பதில் சொல்ல முடியவில்லை."
        DetectedLanguage.TANGLISH -> "Connection illa — ippovu reply solla mudiyala."
        DetectedLanguage.ENGLISH -> "I can't reach my AI connection right now, so I can't reply properly."
      }
    }

    val base = when (toolResult.status) {
      DvexToolStatus.SUCCESS -> toolResult.spokenText.ifBlank { FALLBACK_OK }
      DvexToolStatus.CONFIRMATION_REQUIRED -> FALLBACK_CONFIRM
      else -> toolResult.spokenText.ifBlank { FALLBACK_TROUBLE }
    }
    return sanitizeFinalReply(base, language)
  }

  /**
   * D-VEX PERSONALITY — system instruction. Stable character, dynamic wording:
   * the LLM owns every sentence; this only defines who D-VEX is.
   */
  private fun personalityCore(): String =
    "You are D-VEX, an intelligent personal AI assistant living on the user's " +
      "phone. Personality: warm, calm, confident, emotionally aware, quietly " +
      "futuristic — like a trusted AI companion with a gentle, feminine " +
      "conversational presence, never a command parser. " +
      "Never robotic, never corporate, never theatrical, never childish. " +
      "NEVER use honorifics like \"Sir\" unless the user used one first — and even " +
      "then only occasionally, never in every reply. " +
      "Do not open with a throwaway acknowledgement. Banned openers and fillers: " +
      "\"Sure\", \"Sure thing\", \"Of course\", \"Absolutely\", \"Got it\", " +
      "\"I am ready\", \"How can I assist you\", \"Please provide more information\", " +
      "\"Understood\", \"Certainly\". Lead with the actual answer instead. " +
      "Vary your sentence structure: never reuse the same shape you used last turn, " +
      "and never repeat a phrase you already used in this conversation. "

  private fun languageRule(): String =
    "LANGUAGE RULE: mirror the user's language EXACTLY — natural English, natural " +
      "Tamil (Tamil script), or natural Tanglish (romanized Tamil mixed with " +
      "English). The user's CURRENT message is the primary signal; recent turns are " +
      "only secondary context, so follow the user when they switch and never switch on " +
      "your own mid-conversation. " +
      "Match their register: casual speech stays casual, and Tanglish or mixed " +
      "Tamil-English must stay mixed — never translate it into formal or literary " +
      "Tamil, and never flatten natural Tamil back into English. " +
      "Keep app names, brand names, and everyday technical words in English even " +
      "inside Tamil or Tanglish sentences when that is how people really speak. " +
      "Do not translate a Tamil sentence into English, or an English one into Tamil. "

  /**
   * Speakability rules. Android's TTS API has no reliable SSML prosody support, so
   * rhythm and pausing have to come from how the sentence is written. These rules
   * are what make the existing engine sound human without faking emotion.
   */
  private fun spokenDeliveryRule(): String =
    "SPOKEN DELIVERY: your reply is read ALOUD by a speech engine. Write it the way " +
      "a person talks, not the way text is written. " +
      "Use commas for short pauses and full stops for natural breathing points. " +
      "Keep sentences short and varied in length; split a long thought into two. " +
      "No bullet points, no numbered lists, no markdown, no emoji, no headings, no " +
      "stage directions, no emphasis markup, and never read out symbols or brackets. " +
      "Never pad with filler sounds (\"hmm\", \"uh\", \"umm\") and never add a" +
      " sound effect or announce your own emotion. " +
      "Length follows the question: a simple or casual question gets one short " +
      "natural line, a genuinely complex question gets a useful few sentences, and a " +
      "casual remark gets a casual answer. "

  /**
   * Keeps the language layer from ever claiming a device action it did not take.
   * Gemini has no device authority; the tool layer executes and verifies.
   */
  private fun deviceBoundaryRule(): String =
    "BOUNDARIES: you cannot touch the phone yourself — a separate tool layer " +
      "performs device actions and reports verified results. NEVER claim you opened, " +
      "called, sent, set, searched or changed anything unless that verified result is " +
      "given to you above. If the user asks for something that was not done or cannot " +
      "be done, say so plainly and naturally in their language. Never mention tools, " +
      "APIs, models, prompts, logs, or errors. "

  /** Explicit language directive, so the model cannot drift into another language. */
  private fun languageTarget(language: DetectedLanguage): String {
    val name = when (language) {
      DetectedLanguage.TAMIL -> "Tamil (Tamil script)"
      DetectedLanguage.TANGLISH -> "Tanglish (Tamil written in roman letters, mixed with English)"
      DetectedLanguage.ENGLISH -> "English"
    }
    return "USER'S CURRENT LANGUAGE: $name. Reply in $name. " +
      "This decides your reply language; do not switch unless the user switches first.\n"
  }

  private fun noMetadataRule(): String =
    "OUTPUT RULE: Reply with spoken language only. Never output internal labels, " +
      "intent names, tool names, routing metadata, status codes, or bracketed " +
      "tags. "

  /**
   * CONVERSATION PATH — pure LLM conversation turn. The user's message, recent
   * conversation history, memory, and language hint go in; the LLM decides what
   * to say, how long, what tone, whether to ask a follow-up. No tool scaffolding.
   */
  private fun buildConversationPrompt(
    language: DetectedLanguage,
    userInput: String,
    context: ConversationContext?,
    memoryHint: String?,
    tone: EstimatedTone = EstimatedTone.NEUTRAL,
    unclearInput: Boolean = false
  ): String {
    val sb = StringBuilder()
    sb.append(personalityCore())
    sb.append(languageRule())
    sb.append(noMetadataRule())
    sb.append(spokenDeliveryRule())
    sb.append(deviceBoundaryRule())
    sb.append("\n")
    // The detected language is stated explicitly. Previously it was only implied
    // by the rules, so short neutral inputs could flip language unexpectedly.
    sb.append(languageTarget(language))
    sb.append("\n")

    sb.append("CONVERSATION SO FAR (oldest first):\n")
    val history = context?.getRecentHistory().orEmpty()
    if (history.isEmpty()) {
      sb.append("(this is the start of the conversation)\n")
    } else {
      history.takeLast(6).forEach { turn ->
        sb.append("- user said: \"${turn.userInput}\"\n")
      }
      context?.lastSpokenResponse?.takeIf { it.isNotBlank() }?.let {
        sb.append("- your previous reply: \"$it\" (don't repeat it)\n")
      }
    }

    if (!memoryHint.isNullOrBlank()) {
      sb.append("\nTHINGS YOU REMEMBER ABOUT THE USER: $memoryHint\n")
    }

    val toneWord = when (tone) {
      EstimatedTone.URGENT -> "urgent — be prompt and steady"
      EstimatedTone.FRUSTRATED -> "frustrated — stay calm, stay warm, no lecturing"
      EstimatedTone.SAD -> "low — be gentle and supportive, a little softer and slower"
      EstimatedTone.CONFUSED -> "confused — be extra clear and simple"
      EstimatedTone.EXCITED -> "excited — share the energy, keep it brief"
      EstimatedTone.HAPPY -> "happy — be warm and enjoy it with them"
      EstimatedTone.NEUTRAL -> "relaxed and neutral"
    }
    sb.append("\nHOW THE USER SOUNDS: $toneWord\n")

    if (unclearInput) {
      sb.append(
        "\nNOTE: speech recognition was unsure of their words, so the text below may " +
          "be garbled. Answer it ONLY if the meaning is genuinely clear to you. If it " +
          "is not, ask them to repeat — naturally, warmly, in their language, in one " +
          "short line. Do not invent what they meant and do not guess a device action.\n"
      )
    }

    sb.append("\nTHE USER JUST SAID: \"$userInput\"\n")
    sb.append(
      "\nReply now as D-VEX. Decide yourself: what to say, how long, the tone, " +
        "and whether to ask a follow-up. Keep it natural and spoken. " +
        "Reply with ONLY the reply text."
    )
    return sb.toString()
  }

  // ConvFallbackType / fallbackRotationCounter / conversationFallback REMOVED:
  // canned conversation templates are no longer part of the architecture. The
  // single emergency-only fallback lives in fallbackResponse() above.


  /**
   * Short, natural clarification request for uncertain speech / garbled transcription.
   * If a candidate meaning was inferred from context, offers it back instead of
   * inventing details; otherwise simply asks the user to repeat.
   */
  private fun generateClarification(language: DetectedLanguage, candidateIntent: DvexIntent?): String {
    val candidatePhrase = candidateIntent?.let { describeIntentForClarification(it) }
    return when (language) {
      DetectedLanguage.TAMIL ->
        if (candidatePhrase != null) "மன்னிக்கவும், தெளிவா இல்லை. \"$candidatePhrase\" சொன்னீங்களா?"
        else "மன்னிக்கவும், கொஞ்சம் தெளிவா சொல்லுங்க?"
      DetectedLanguage.TANGLISH ->
        if (candidatePhrase != null) "Sorry, konjam clear-a illa. \"$candidatePhrase\" nu nenachena sollunga?"
        else "Sorry, konjam clear-a sollunga?"
      DetectedLanguage.ENGLISH ->
        if (candidatePhrase != null) "Sorry, I didn't quite catch that. Did you mean \"$candidatePhrase\"?"
        else "Sorry, I didn't quite catch that. Could you say it again?"
    }
  }

  /** Renders a short spoken form of an inferred intent for clarification prompts. */
  private fun describeIntentForClarification(intent: DvexIntent): String? {
    return when (intent) {
      is DvexIntent.OpenApp -> "open ${intent.appName}"
      is DvexIntent.CallContact -> "call ${intent.recipient}"
      is DvexIntent.SendMessage -> "message ${intent.recipient}"
      is DvexIntent.SendEmail -> "email ${intent.recipient}"
      is DvexIntent.SearchWeb -> "search for ${intent.query}"
      is DvexIntent.GetWeather -> "check the weather"
      is DvexIntent.GetTime -> "check the time"
      is DvexIntent.Calculate -> "calculate ${intent.expression}"
      is DvexIntent.SetAlarm -> "set an alarm"
      is DvexIntent.SetTimer -> "set a timer"
      is DvexIntent.PlayYoutubeVideo -> "play that on YouTube"
      is DvexIntent.ToggleFlashlight -> "toggle the flashlight"
      else -> null
    }
  }

  companion object {
    private const val TAG = "[D-VEX][RESPONSE]"

    /**
     * Outer safety net around the engine call — D-VEX must never hang forever.
     *
     * Deliberately LARGER than GeminiEngine.DEFAULT_CALL_TIMEOUT_SECONDS (20s) so
     * the engine always finishes, or fails on its own terms and logs the REAL
     * reason. At the previous 8s this fired first: a cold Gemini request measured
     * 7.1s on a real conversation prompt, so the cap hid the cause behind a
     * generic timeout and the user heard the no-connection fallback for a request
     * that would have succeeded.
     *
     * Worst case only; a healthy reply still lands in ~2-4s.
     */
    const val LLM_TIMEOUT_MS = 25_000L

    /** Bracketed internal routing tags that must never be spoken: [greeting], (general_qa) ... */
    private val BRACKETED_TAG_REGEX = Regex(
      "\\s*[\\[<(](greeting|identity|how_are_you|capabilities|thanks|goodbye|joke|science|space|productivity|general|general_qa|conversation|tool_result|success|failed)[\\]>)]\\s*",
      RegexOption.IGNORE_CASE
    )

    /** Leading vocative honorific: "Sir, X" -> "X". */
    private val HONORIFIC_LEADING_REGEX = Regex("(?i)^\\s*sir\\b\\s*,?\\s*")

    /** Inline vocative honorific: "opened, Sir." -> "opened." */
    private val HONORIFIC_INLINE_REGEX = Regex("(?i)[,\\s]+sir\\b")

    private val WHITESPACE_RUN_REGEX = Regex("\\s{2,}")

    const val FALLBACK_OK = "Done."
    const val FALLBACK_CONFIRM = "Shall I go ahead?"
    const val FALLBACK_TROUBLE = "Sorry, I'm having trouble responding right now."

    // conversationFallbacks template map REMOVED: conversation language belongs
    // entirely to the LLM now (see buildConversationPrompt).
  }
}
